# 配置端口
server:
  port: 8082
  servlet:
    context-path: /ceph

# ceph存储相关信息配置
ceph:
  config:
    hosts: http://10.40.7.78:7480/
    accessKey: BPVDG8K060D72KQR8P2K
    secretKey: sExAV2xdVz7ubvFNGCoRAU9mktWEMxBMRhdVR57H
    bucketName: chenoss6d1b6bcd

logging:
  level:
    com.roylao: DEBUG